name: Terraform Local File Example

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-local:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform-local
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform-local
        run: terraform apply -auto-approve

      - name: Show file content
        run: ls -lR
